# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668846c1e0c00e90f3b1811cb92ef1ab5712217274aa0e26cb702b7e09bcf82c39fdd8714722954e018ddbd57f2f32f50cc94859f50c02fd24afb38f1b5b6a55

test:
  secret_key_base: 4c1f256bb37e305d084037c3bfa03777822176d7ed6117c66ef1bd7edc053f59232fac258c25cd425025f9cf7594f50a541ac8935f838da96f1650bdfdb803af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
